### ISSUE TITLE
AttributeError: 'StableDiffusionControlNetPipeline' object has no attribute 'load_ip_adapter'

### ISSUE THREAD

**Issue by pranaykoppula** [tencent-ailab/IP-Adapter#178]
Ran into this error while trying to load an IP Adapter in Google Colab, even though I followed the syntax from here:
https://huggingface.co/docs/diffusers/main/en/using-diffusers/loading_adapters#ip-adapter

**Error message:** 

---> 11 pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter-plus_sdxl_vit-h.bin")
     12 
     13 generator = torch.Generator(device="cpu").manual_seed(33)

[/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py](https://localhost:8080/#) in __getattr__(self, name)
    135             return self._internal_dict[name]
    136 
--> 137         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    138 
    139     def save_config(self, save_directory: Union[str, os.PathLike], push_to_hub: bool = False, **kwargs):

AttributeError: 'StableDiffusionControlNetPipeline' object has no attribute 'load_ip_adapter'

**Comment by xiaohu2015** [comment]
do you use latest version of diffusers?

**Comment by pranaykoppula** [comment]
> do you use latest version of diffusers?

Thank you, I was following the official installation instructions so I installed version 0.22. I fixed that but now I'm getting the same error as the one in issue #6131

**Error Message:**

KeyError                                  Traceback (most recent call last)
[<ipython-input-5-71db715289e5>](https://localhost:8080/#) in <cell line: 7>()
      5 openpose_image=openpose(openpose_image).resize(init_image.size)
      6 from ip_adapter import IPAdapterXL
----> 7 pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter-plus_sdxl_vit-h.bin")
      8 
      9 generator = torch.Generator(device="cpu").manual_seed(33)

1 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/loaders/ip_adapter.py](https://localhost:8080/#) in load_ip_adapter(self, pretrained_model_name_or_path_or_dict, subfolder, weight_name, **kwargs)
    150 
    151         # load ip-adapter into unet
--> 152         self.unet._load_ip_adapter_weights(state_dict)
    153 
    154     def set_ip_adapter_scale(self, scale):

[/usr/local/lib/python3.10/dist-packages/diffusers/loaders/unet.py](https://localhost:8080/#) in _load_ip_adapter_weights(self, state_dict)
    709 
    710         # create image projection layers.
--> 711         clip_embeddings_dim = state_dict["image_proj"]["proj.weight"].shape[-1]
    712         cross_attention_dim = state_dict["image_proj"]["proj.weight"].shape[0] // 4
    713 

KeyError: 'proj.weight'

**Comment by xiaohu2015** [comment]
pip install git+https //github.com/huggingface/diffusers, try this?

**Comment by pranaykoppula** [comment]
I just tried pip install diffusers, which installed v 0.24.0

Since this error seems specific to IP Adapter Plus, I just used the regular adapter for SDXL

- StableDiffusionXLControlNetImg2ImgPipeline has no attribute 'load_ip_adapter',
- StableDiffusionXLControlNetPipeline loads the adapter successfully but before a single step of inference is done, it gives the following error: 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1280 and 1024x8192)

I thought the issue was with my images and resized them to 1024x1024, and just guessing based on the error message, I resized them to 1280x1280, but neither change had any effect

I'm no longer sure if the issue is with SDXL, ControlNet or IP-Adapter, so I think I'm just gonna try to work with SD1.5 for now.

Here's the error message I was talking about:

 RuntimeError                              Traceback (most recent call last)
[<ipython-input-7-21d12608574a>](https://localhost:8080/#) in <cell line: 11>()
      9 pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter_sdxl_vit-h.bin")
     10 generator = torch.Generator(device="cpu").manual_seed(33)
---> 11 images = pipeline(
     12     prompt='best quality, high quality',
     13     image=openpose_image,

10 frames
[/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py](https://localhost:8080/#) in __call__(self, prompt, prompt_2, image, height, width, num_inference_steps, guidance_scale, negative_prompt, negative_prompt_2, num_images_per_prompt, eta, generator, latents, prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds, ip_adapter_image, output_type, return_dict, cross_attention_kwargs, controlnet_conditioning_scale, guess_mode, control_guidance_start, control_guidance_end, original_size, crops_coords_top_left, target_size, negative_original_size, negative_crops_coords_top_left, negative_target_size, clip_skip, callback_on_step_end, callback_on_step_end_tensor_inputs, **kwargs)
   1352 
   1353                 # predict the noise residual
-> 1354                 noise_pred = self.unet(
   1355                     latent_model_input,
   1356                     t,

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

[/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py](https://localhost:8080/#) in forward(self, sample, timestep, encoder_hidden_states, class_labels, timestep_cond, attention_mask, cross_attention_kwargs, added_cond_kwargs, down_block_additional_residuals, mid_block_additional_residual, down_intrablock_additional_residuals, encoder_attention_mask, return_dict)
   1029                 )
   1030             image_embeds = added_cond_kwargs.get("image_embeds")
-> 1031             image_embeds = self.encoder_hid_proj(image_embeds).to(encoder_hidden_states.dtype)
   1032             encoder_hidden_states = torch.cat([encoder_hidden_states, image_embeds], dim=1)
   1033 

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

[/usr/local/lib/python3.10/dist-packages/diffusers/models/embeddings.py](https://localhost:8080/#) in forward(self, image_embeds)
    455 
    456         # image
--> 457         image_embeds = self.image_embeds(image_embeds)
    458         image_embeds = image_embeds.reshape(batch_size, self.num_image_text_embeds, -1)
    459         image_embeds = self.norm(image_embeds)

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs)
   1516             return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517         else:
-> 1518             return self._call_impl(*args, **kwargs)
   1519 
   1520     def _call_impl(self, *args, **kwargs):

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1525                 or _global_backward_pre_hooks or _global_backward_hooks
   1526                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527             return forward_call(*args, **kwargs)
   1528 
   1529         try:

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py](https://localhost:8080/#) in forward(self, input)
    112 
    113     def forward(self, input: Tensor) -> Tensor:
--> 114         return F.linear(input, self.weight, self.bias)
    115 
    116     def extra_repr(self) -> str:

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1280 and 1024x8192)

**Comment by xiaohu2015** [comment]
> I just tried pip install diffusers, which installed v 0.24.0
> 
> Since this error seems specific to IP Adapter Plus, I just used the regular adapter for SDXL
> 
> * StableDiffusionXLControlNetImg2ImgPipeline has no attribute 'load_ip_adapter',
> * StableDiffusionXLControlNetPipeline loads the adapter successfully but before a single step of inference is done, it gives the following error:
> 
> RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1280 and 1024x8192)
> 
> I thought the issue was with my images and resized them to 1024x1024, and just guessing based on the error message, I resized them to 1280x1280, but neither change had any effect
> 
> I'm no longer sure if the issue is with SDXL, ControlNet or IP-Adapter, so I think I'm just gonna try to work with SD1.5 for now.
> 
> Here's the error message I was talking about:
> 
> RuntimeError Traceback (most recent call last) in <cell line: 11>() 9 pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter_sdxl_vit-h.bin") 10 generator = torch.Generator(device="cpu").manual_seed(33) ---> 11 images = pipeline( 12 prompt='best quality, high quality', 13 image=openpose_image,
> 
> 10 frames [/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py](https://localhost:8080/#) in decorate_context(*args, **kwargs) 113 def decorate_context(*args, **kwargs): 114 with ctx_factory(): --> 115 return func(*args, **kwargs) 116 117 return decorate_context
> 
> [/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py](https://localhost:8080/#) in **call**(self, prompt, prompt_2, image, height, width, num_inference_steps, guidance_scale, negative_prompt, negative_prompt_2, num_images_per_prompt, eta, generator, latents, prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds, ip_adapter_image, output_type, return_dict, cross_attention_kwargs, controlnet_conditioning_scale, guess_mode, control_guidance_start, control_guidance_end, original_size, crops_coords_top_left, target_size, negative_original_size, negative_crops_coords_top_left, negative_target_size, clip_skip, callback_on_step_end, callback_on_step_end_tensor_inputs, **kwargs) 1352 1353 # predict the noise residual -> 1354 noise_pred = self.unet( 1355 latent_model_input, 1356 t,
> 
> [/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs) 1516 return self._compiled_call_impl(*args, **kwargs) # type: ignore[misc] 1517 else: -> 1518 return self._call_impl(*args, **kwargs) 1519 1520 def _call_impl(self, *args, **kwargs):
> 
> [/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs) 1525 or _global_backward_pre_hooks or _global_backward_hooks 1526 or _global_forward_hooks or _global_forward_pre_hooks): -> 1527 return forward_call(*args, **kwargs) 1528 1529 try:
> 
> [/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py](https://localhost:8080/#) in forward(self, sample, timestep, encoder_hidden_states, class_labels, timestep_cond, attention_mask, cross_attention_kwargs, added_cond_kwargs, down_block_additional_residuals, mid_block_additional_residual, down_intrablock_additional_residuals, encoder_attention_mask, return_dict) 1029 ) 1030 image_embeds = added_cond_kwargs.get("image_embeds") -> 1031 image_embeds = self.encoder_hid_proj(image_embeds).to(encoder_hidden_states.dtype) 1032 encoder_hidden_states = torch.cat([encoder_hidden_states, image_embeds], dim=1) 1033
> 
> [/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs) 1516 return self._compiled_call_impl(*args, **kwargs) # type: ignore[misc] 1517 else: -> 1518 return self._call_impl(*args, **kwargs) 1519 1520 def _call_impl(self, *args, **kwargs):
> 
> [/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs) 1525 or _global_backward_pre_hooks or _global_backward_hooks 1526 or _global_forward_hooks or _global_forward_pre_hooks): -> 1527 return forward_call(*args, **kwargs) 1528 1529 try:
> 
> [/usr/local/lib/python3.10/dist-packages/diffusers/models/embeddings.py](https://localhost:8080/#) in forward(self, image_embeds) 455 456 # image --> 457 image_embeds = self.image_embeds(image_embeds) 458 image_embeds = image_embeds.reshape(batch_size, self.num_image_text_embeds, -1) 459 image_embeds = self.norm(image_embeds)
> 
> [/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _wrapped_call_impl(self, *args, **kwargs) 1516 return self._compiled_call_impl(*args, **kwargs) # type: ignore[misc] 1517 else: -> 1518 return self._call_impl(*args, **kwargs) 1519 1520 def _call_impl(self, *args, **kwargs):
> 
> [/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs) 1525 or _global_backward_pre_hooks or _global_backward_hooks 1526 or _global_forward_hooks or _global_forward_pre_hooks): -> 1527 return forward_call(*args, **kwargs) 1528 1529 try:
> 
> [/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py](https://localhost:8080/#) in forward(self, input) 112 113 def forward(self, input: Tensor) -> Tensor: --> 114 return F.linear(input, self.weight, self.bias) 115 116 def extra_repr(self) -> str:
> 
> RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1280 and 1024x8192)

it seems you use wrong image encoder

**Comment by pranaykoppula** [comment]
Thank you.
